export default [
  {
    id: 1,
    title: "StarryNights #0001",
    description: "",
    price: 0.61,
    coverImg: "starryNights_(1).png",
    extras: {
      reviewCount: 32,
      favoriteCount: 1,
      saleEnd: "September 22, 2022 at 7:59am GMT+3",
    },
    ownedBy: "F68468",
  },
  {
    id: 2,
    title: "StarryNights #0002",
    description: "",
    price: 0.63,
    coverImg: "starryNights_(2).png",
    extras: {
      reviewCount: 68,
      favoriteCount: 2,
      saleEnd: "September 18, 2022 at 7:33am GMT+3",
    },
    ownedBy: "F63037",
  },
  {
    id: 3,
    title: "StarryNights #0003",
    description: "",
    price: 0.65,
    coverImg: "starryNights_(3).png",
    extras: {
      reviewCount: 158,
      favoriteCount: 3,
      saleEnd: "September 19, 2022 at 7:10pm GMT+3",
    },
    ownedBy: "006DB6",
  },
  {
    id: 4,
    title: "StarryNights #0004",
    description: "",
    price: 0.675,
    coverImg: "starryNights_(4).png",
    extras: {
      reviewCount: 180,
      favoriteCount: 1,
      saleEnd: "September 16, 2022 at 10:56am GMT+3",
    },
    ownedBy: "S5868A",
  },
  {
    id: 5,
    title: "StarryNights #0005",
    description: "",
    price: 0.69,
    coverImg: "starryNights_(5).png",
    extras: {
      reviewCount: 189,
      favoriteCount: 5,
      saleEnd: "September 16, 2022 at 5:29am GMT+3",
    },
    ownedBy: "31FCA5",
  },
  {
    id: 6,
    title: "StarryNights #0006",
    description: "",
    price: 0.75,
    coverImg: "starryNights_(6).png",
    extras: {
      reviewCount: 201,
      favoriteCount: 3,
      saleEnd: "September 16, 2022 at 5:30am GMT+3",
    },
    ownedBy: "97F245",
  },
  {
    id: 7,
    title: "StarryNights #0007",
    description: "",
    price: 0.82,
    coverImg: "starryNights_(7).png",
    extras: {
      reviewCount: 228,
      favoriteCount: 2,
      saleEnd: "September 18, 2022 at 3:17am GMT+3",
    },
    ownedBy: "B8CCA7",
  },
  {
    id: 8,
    title: "StarryNights #0008",
    description: "",
    price: 0.96,
    coverImg: "starryNights_(8).png",
    extras: {
      reviewCount: 278,
      favoriteCount: 1,
      saleEnd: "August 30, 2022 at 6:01am GMT+3",
    },
    ownedBy: "B8CCA7",
  },
  {
    id: 9,
    title: "StarryNights #0009",
    description: "",
    price: 1.24,
    coverImg: "starryNights_(9).png",
    extras: {
      reviewCount: 368,
      favoriteCount: 3,
      saleEnd: "September 16, 2022 at 5:30pm GMT+3",
    },
    ownedBy: "98B7AD",
  },
  {
    id: 10,
    title: "StarryNights #0010",
    description: "",
    price: 1.26,
    coverImg: "starryNights_(10).png",
    extras: {
      reviewCount: 124,
      favoriteCount: 3,
      saleEnd: "September 17, 2022 at 5:30pm GMT+3",
    },
    ownedBy: "98FA85",
  },
  {
    id: 11,
    title: "StarryNights #0011",
    description: "",
    price: 1.32,
    coverImg: "starryNights_(11).png",
    extras: {
      reviewCount: 132,
      favoriteCount: 3,
      saleEnd: "September 18, 2022 at 5:30pm GMT+3",
    },
    ownedBy: "FS6858",
  },
  {
    id: 12,
    title: "StarryNights #0012",
    description: "",
    price: 1.34,
    coverImg: "starryNights_(12).png",
    extras: {
      reviewCount: 140,
      favoriteCount: 3,
      saleEnd: "September 19, 2022 at 5:30pm GMT+3",
    },
    ownedBy: "S586A2",
  },
];
